// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMS.EFCore;

#nullable disable

namespace WMS.EFCore.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20231122012110_init5")]
    partial class init5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WMS.Domain.Entity.Bs.Bs_ware_area", b =>
                {
                    b.Property<int>("ware_area_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ware_area_id"));

                    b.Property<int>("area_cap")
                        .HasColumnType("int");

                    b.Property<string>("area_code")
                        .HasColumnType("char(6)");

                    b.Property<string>("area_duty_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("area_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("area_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("is_del")
                        .HasColumnType("char(1)");

                    b.Property<int>("sort_code")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("ware_area_id");

                    b.ToTable("Bs_ware_area", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Bs.Bs_warehouse", b =>
                {
                    b.Property<int>("warehouse_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("warehouse_id"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("is_default")
                        .HasColumnType("char(1)");

                    b.Property<string>("is_del")
                        .HasColumnType("char(1)");

                    b.Property<int>("is_lock")
                        .HasColumnType("int");

                    b.Property<int>("sort_code")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.Property<string>("ware_adr")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ware_cap")
                        .HasColumnType("int");

                    b.Property<string>("ware_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("ware_code3")
                        .HasColumnType("char(6)");

                    b.Property<string>("ware_duty_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ware_state")
                        .HasColumnType("char(1)");

                    b.HasKey("warehouse_id");

                    b.ToTable("Bs_warehouse", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Cm.Bs_item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_id"));

                    b.Property<decimal>("above_up")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("below_down")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("inbill_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("inbill_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("is_del")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("item_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<int>("item_down")
                        .HasColumnType("int");

                    b.Property<string>("item_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("item_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("item_up")
                        .HasColumnType("int");

                    b.Property<string>("model_code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("outbill_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("sort_code")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("item_id");

                    b.ToTable("Bs_item", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Cm.Bs_item_type", b =>
                {
                    b.Property<int>("item_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_type_id"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("father_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("inbill_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("is_del")
                        .HasColumnType("char(1)");

                    b.Property<string>("item_type_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("item_type_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("sort_code")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("item_type_id");

                    b.ToTable("Bs_item_type", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.KC.Wh_now_storage", b =>
                {
                    b.Property<string>("ware_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("area_code")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("inbill3_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .HasColumnType("char(8)");

                    b.Property<int>("now_storage_id")
                        .HasColumnType("int");

                    b.Property<decimal>("plan_outnum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ware_code");

                    b.ToTable("Wh_now_storage", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_inbill_d", b =>
                {
                    b.Property<int>("inbill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inbill_id"));

                    b.Property<string>("area_code")
                        .HasColumnType("char(6)");

                    b.Property<string>("batch_no")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("buy_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("buy_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<int>("inbill_code")
                        .HasColumnType("int");

                    b.Property<decimal>("inbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("item_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("product_date")
                        .HasColumnType("datetime");

                    b.Property<string>("unit")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("inbill_id");

                    b.ToTable("Wh_inbill_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_inbill_h", b =>
                {
                    b.Property<int>("inbill_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inbill_code"));

                    b.Property<string>("buy_code")
                        .HasColumnType("char(16)");

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("inbill_duty_man")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("inbill_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("inbill_type")
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("inbll_date")
                        .HasColumnType("datetime");

                    b.Property<string>("is_del")
                        .HasColumnType("char(1)");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_way")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("supply_code")
                        .HasColumnType("char(9)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("inbill_code");

                    b.ToTable("Wh_inbill_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_inventory_d", b =>
                {
                    b.Property<int>("inventory_d_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inventory_d_id"));

                    b.Property<decimal>("account_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("area_code")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("break_even_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("inbill_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("inventory_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<decimal>("inventory_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("inventory_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("item_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("item_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("model_code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("unit")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("inventory_d_id");

                    b.ToTable("Wh_inventory_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_inventory_h", b =>
                {
                    b.Property<int>("inventory_h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inventory_h_id"));

                    b.Property<DateTime>("begin_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime");

                    b.Property<string>("inventory_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<string>("inventory_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("ware_code")
                        .HasColumnType("char(8)");

                    b.HasKey("inventory_h_id");

                    b.ToTable("Wh_inventory_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_outbill_d", b =>
                {
                    b.Property<int>("outbill_d_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("outbill_d_id"));

                    b.Property<string>("area_code")
                        .HasColumnType("char(6)");

                    b.Property<string>("barcode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("batch_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("item_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("item_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("outbill_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<decimal>("outbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("product_date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("sale_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unit")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("outbill_d_id");

                    b.ToTable("Wh_outbill_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_outbill_h", b =>
                {
                    b.Property<int>("outbill_h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("outbill_h_id"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("cust_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("duty_man")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_way")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("outbill_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("outbill_date")
                        .HasColumnType("datetime");

                    b.Property<string>("outbill_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("sale_code")
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("update_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("update_time")
                        .HasColumnType("datetime");

                    b.Property<string>("ware_code")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("outbill_h_id");

                    b.ToTable("Wh_outbill_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_transfer_d", b =>
                {
                    b.Property<int>("transfer_d_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transfer_d_id"));

                    b.Property<int>("in_num")
                        .HasColumnType("int");

                    b.Property<string>("inarea_code")
                        .HasColumnType("char(6)");

                    b.Property<decimal>("inbill_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("model_code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("out_num")
                        .HasColumnType("int");

                    b.Property<string>("outarea_code")
                        .HasColumnType("char(6)");

                    b.Property<string>("transfer_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<string>("unit")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("wh__transfer_code")
                        .HasColumnType("char(16)");

                    b.HasKey("transfer_d_id");

                    b.ToTable("Wh_transfer_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Ku.Wh_transfer_h", b =>
                {
                    b.Property<int>("transfer_h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transfer_h_id"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("in_warecode")
                        .HasColumnType("char(8)");

                    b.Property<string>("inware_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("out_warecode")
                        .HasColumnType("char(8)");

                    b.Property<string>("outware_state")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("transfer_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("transfer_date")
                        .HasColumnType("datetime");

                    b.Property<string>("transfer_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("transfer_h_id");

                    b.ToTable("Wh_transfer_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Pc.Wh_batch_storage", b =>
                {
                    b.Property<int>("batch_storage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("batch_storage_id"));

                    b.Property<string>("area_code")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("batch_no")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("buy_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("inbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("inbill_type")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("item_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<decimal>("outbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("plan_outbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("product_date")
                        .HasColumnType("datetime");

                    b.Property<string>("unit")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ware_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.HasKey("batch_storage_id");

                    b.ToTable("Wh_batch_storage", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sup.Bs_customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_id"));

                    b.Property<string>("cust_adr")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("cust_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("cust_from")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("cust_name")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("e_mail")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("inbill_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("is_del")
                        .HasColumnType("char(1)");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_tel")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("customer_id");

                    b.ToTable("Bs_customer", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sup.Bs_finance", b =>
                {
                    b.Property<int>("finance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("finance_id"));

                    b.Property<string>("bank_no")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("finance_name")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("finance_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("open_adr")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("open_bank")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("tax_no")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("finance_id");

                    b.ToTable("Bs_finance", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sup.Bs_supply", b =>
                {
                    b.Property<int>("supply_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supply_id"));

                    b.Property<string>("e_mail")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("inbill_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("line_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_tel")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("stock_duty_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("supply_adr")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("supply_code")
                        .IsRequired()
                        .HasColumnType("char(9)");

                    b.Property<string>("supply_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("supply_type_code")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("supply_id");

                    b.ToTable("Bs_supply", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sys.Sys_attach_file", b =>
                {
                    b.Property<int>("saf_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("saf_id"));

                    b.Property<string>("bill_code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<int>("file_id")
                        .HasColumnType("int");

                    b.Property<string>("file_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("file_url")
                        .HasMaxLength(225)
                        .IsUnicode(false)
                        .HasColumnType("varchar(225)");

                    b.HasKey("saf_id");

                    b.ToTable("Sys_attach_file", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sys.Sys_dict_data", b =>
                {
                    b.Property<int>("dict_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dict_code"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("dict_label")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dict_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dict_type")
                        .HasColumnType("char(1)");

                    b.Property<string>("dict_value")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("is_default")
                        .HasColumnType("char(1)");

                    b.Property<string>("remark")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("status")
                        .HasColumnType("char(1)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("dict_code");

                    b.ToTable("Sys_dict_data", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sys.Sys_dict_type", b =>
                {
                    b.Property<int>("dict_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dict_id"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("dict_label")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dict_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dict_value")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("dict_id");

                    b.ToTable("Sys_dict_type", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sys.Sys_encode", b =>
                {
                    b.Property<int>("en_step")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("en_step"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<int>("en_code")
                        .HasColumnType("int");

                    b.Property<string>("en_form")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("en_num")
                        .HasColumnType("int");

                    b.Property<string>("en_prefix")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("en_rules")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("en_time")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("is_del")
                        .HasColumnType("char(1)");

                    b.HasKey("en_step");

                    b.ToTable("Sys_encode", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sys.Sys_message", b =>
                {
                    b.Property<int>("msg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("msg_id"));

                    b.Property<string>("deal_url")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("is_read")
                        .HasColumnType("char(1)");

                    b.Property<string>("msg_content")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("msg_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("msg_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("rcv_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("rcv_time")
                        .HasColumnType("datetime");

                    b.Property<string>("send_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("send_time")
                        .HasColumnType("datetime");

                    b.HasKey("msg_id");

                    b.ToTable("Sys_message", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Sys.Sys_wh_warn", b =>
                {
                    b.Property<int>("warn_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("warn_id"));

                    b.Property<string>("notice_man")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("warn_day")
                        .HasColumnType("int");

                    b.Property<DateTime>("warn_time")
                        .HasColumnType("datetime");

                    b.HasKey("warn_id");

                    b.ToTable("Sys_wh_warn", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.User.Authority", b =>
                {
                    b.Property<int>("AuthorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorityID"));

                    b.Property<string>("AuthorityAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.HasKey("AuthorityID");

                    b.ToTable("Authority", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.User.Roles", b =>
                {
                    b.Property<int>("RolesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesID"));

                    b.Property<string>("RolesAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RolesName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RolesState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RolesID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.User.RolesAuthority", b =>
                {
                    b.Property<int>("RolesAuthorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesAuthorityID"));

                    b.Property<int>("AuthorityID")
                        .HasColumnType("int");

                    b.Property<int>("RolesID")
                        .HasColumnType("int");

                    b.HasKey("RolesAuthorityID");

                    b.ToTable("RolesAuthority", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.User.UserRoles", b =>
                {
                    b.Property<int>("UserRolesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRolesID"));

                    b.Property<int>("RolesID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserRolesID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.User.Users", b =>
                {
                    b.Property<int>("U_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("U_id"));

                    b.Property<string>("U_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_True_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("U_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("U_password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("U_id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_buy_order_h", b =>
                {
                    b.Property<int>("buy_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("buy_codeId"));

                    b.Property<string>("buy_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("buy_date")
                        .HasColumnType("datetime");

                    b.Property<string>("buy_man")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_way")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("supply_code")
                        .HasColumnType("char(9)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("buy_codeId");

                    b.ToTable("Wh_buy_order_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_orderbuy_d", b =>
                {
                    b.Property<int>("buy_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("buy_codeId"));

                    b.Property<string>("buy_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<decimal>("buy_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("inbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("item_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("item_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("model_code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("return_goods_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unit")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("buy_codeId");

                    b.ToTable("Wh_orderbuy_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_return_supply_d", b =>
                {
                    b.Property<int>("item_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_codeId"));

                    b.Property<string>("batch_no")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("buy_price")
                        .HasMaxLength(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("model_code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("return_goods_num")
                        .HasMaxLength(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("return_money")
                        .HasMaxLength(18)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("item_codeId");

                    b.ToTable("Wh_return_supply_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_return_supply_h", b =>
                {
                    b.Property<int>("buy_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("buy_codeId"));

                    b.Property<string>("buy_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<string>("buy_man")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("buy_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("create_by")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_way")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("returns_money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("returns_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sale_state")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("sr_date")
                        .HasColumnType("datetime");

                    b.Property<string>("supply_code")
                        .HasColumnType("char(9)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .HasColumnType("char(1)");

                    b.Property<string>("update_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("datetime");

                    b.HasKey("buy_codeId");

                    b.ToTable("Wh_return_supply_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_sale_d", b =>
                {
                    b.Property<int>("sale_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sale_codeId"));

                    b.Property<decimal>("inbill3_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("item_type")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("model_code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("outbill_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("return_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sale_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unit")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("sale_codeId");

                    b.ToTable("Wh_sale_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_sale_h", b =>
                {
                    b.Property<int>("sale_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sale_codeId"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("cust_code")
                        .HasColumnType("char(8)");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_way")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("sale_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("sale_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sale_duty_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sale_state")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("sale_codeId");

                    b.ToTable("Wh_sale_h", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_sale_return_d", b =>
                {
                    b.Property<int>("sr_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sr_codeId"));

                    b.Property<string>("area_code")
                        .HasColumnType("char(6)");

                    b.Property<string>("batch_no")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("inbill3_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("item_code")
                        .HasColumnType("char(8)");

                    b.Property<decimal>("return_num")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sr_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<string>("ware_code")
                        .HasColumnType("char(8)");

                    b.HasKey("sr_codeId");

                    b.ToTable("Wh_sale_return_d", (string)null);
                });

            modelBuilder.Entity("WMS.Domain.Entity.Wh.Wh_sale_return_h", b =>
                {
                    b.Property<int>("sr_codeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sr_codeId"));

                    b.Property<string>("create_by")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime");

                    b.Property<string>("cust_code")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.Property<string>("link_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("link_way")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("return_money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sale_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<string>("sale_duty_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sr_code")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("sr_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("sure_date")
                        .HasColumnType("datetime");

                    b.Property<string>("sure_man")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sure_state")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("sr_codeId");

                    b.ToTable("Wh_sale_return_h", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
